version: '3'
services:
  ftp:
    container_name: docker-vsftp
    build: .
    volumes:
      - ./data:/home/vsftpd
    ports:
      -  '20:20'
      -  '21:21'
      -  21100-21110:21100-21110
    environment: 
      - FTP_USER=funky
      - FTP_PASS=geekcloud
      - PASV_ADDRESS=0.0.0.0
    restart: always
