version: '3'
services:
  dns:
    container_name: docker-dns
    build: .
    volumes:
      - ./config/resolv.dnsmasq:/etc/resolv.dnsmasq
      - ./config/dnsmasqhosts:/etc/dnsmasqhosts
      - ./config/dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      -  53:53/tcp 
      -  53:53/udp
    cap_add:
      - NET_ADMIN
