version: '3'
services:
    nginx:
        image: registry.cn-hangzhou.aliyuncs.com/geekcloud/nginx
        build:
            context: .
            dockerfile: Dockerfile.nginx
        volumes:
            - "./site:/usr/share/nginx/html"
        ports:
            - "80:80"
        networks:
            - frontend 
        depends_on:
            - php
    php:
        image: registry.cn-hangzhou.aliyuncs.com/geekcloud/php:5.5-fpm
        build:
            context: .
            dockerfile: Dockerfile.php
        environment:
            MYSQL_PASSWORD: Gekc0uld
        volumes:
            - "./site:/usr/share/nginx/html"
        networks:
            - frontend
            - backend
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            TZ : 'Asia/Shanghai'
            MYSQL_ROOT_PASSWORD: 'Gekc0uld'
        command: ['mysqld', '--character-set-server=utf8']
        networks:
            - backend
volumes:
    mysql-data: 
networks:
    frontend:  
    backend: 
